<a href="https://colab.research.google.com/github/vichacker1234/Pyhton_archives/blob/main/Ejemplo_matrices_numeros_aleatorios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**EJEMPLO CON MATRICES**





In [1]:
#imprtar la librería numpy
import numpy as np 

In [3]:
#Definir la matriz A
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
#Mostrar la matriz
print(A)
#Multiplicación por esclar
3*A

[[1 2 3]
 [4 5 6]
 [7 8 9]]


matrix([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]])

In [7]:
#elementos de una matriz
R=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(R)
print(R[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5


**OPERACIONES MATEMÁTICAS BÁSICAS**

In [6]:
#Operaciones básicas en python con la librería mt
import math as mt
a=mt.sqrt(64)
print(a)
b=mt.sqrt(4)
print(b)
c=mt.log10(10000)
print(c)

8.0
2.0
4.0


**GENERACIÓN DE NÚMEROS ALEATORIOS**

In [27]:
#Importar la librería random
import random as rd
#genera un número aleatorio
rd.random()

0.9495377629163707

In [18]:
#uso del for y números 
rd.seed(1596)
y=[None]*10
for i in range(10):
    y[i]=rd.random()
    print(y[i])

0.11115389505961426
0.567263325980188
0.3917222534864804
0.2313102271208649
0.1708570634850467
0.6792081287495434
0.9279126302609739
0.4978019521975907
0.7818061248797941
0.5041229303084376


In [19]:
rd.seed(1596)
y[3]

0.2313102271208649

In [23]:
#Otro ejemplo para números aleatorios 
#genera números aleatorios entre 50 y 100
rd.seed(1596)
x=[None]*10
min=50; max=100
for indice in range(10):
    x[indice]=min +max*rd.random()%(max-min+1)
    print(x[indice])
    

61.115389505961424
55.7263325980188
89.17222534864804
73.13102271208649
67.08570634850467
66.92081287495434
91.7912630260974
99.78019521975907
77.1806124879794
100.41229303084376


In [28]:
#Matriz de ceros y números aleatorios
ceros=np.zeros((4,5)) #matriz de ceros (4x5)
print(ceros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**Construcción de una matriz con números aleatorios**

In [31]:
#Matriz con números aleatorios
aleatorios=np.random.random((4,4))# matriz con numeros aleatorios
print(aleatorios)

[[0.647861   0.00789231 0.43772772 0.74238607]
 [0.90050403 0.51949823 0.33171465 0.31639708]
 [0.28221014 0.32829107 0.08348688 0.99517964]
 [0.64078938 0.54315115 0.22015156 0.5194213 ]]
